#!/bin/bash
#Script:    Challenge Ops 05
#Author:    Cristiano Garcia
#Date:      13/10/2023

backup_dir="/var/log/backups"
timestamp=$(date +"%Y%m%d%H%M%S")

#Files directory
log_files=(
  "/var/log/syslog"
  "/var/log/wtmp"
)

#Create backup directory
mkdir -p "$backup_dir"


declare -a original_sizes

#File sizes before compression
for file in "${log_files[@]}"; do
original_sizes[$file]=$(du -b "$file" | awk '{print $1}')
done

#Compress files
for file in "${log_files[@]}"; do
  #Tamanho original
  original_size=${original_sizes[$file]}
  
  #File compressed
  filename=$(basename "$file")
  gzip -c "$file" > "$backup_dir/$filename-$timestamp.gz"

  #Erase original 
  rm "$file"

  #Get compressed file
  compressed_size=$(du -b "$backup_dir/$filename-$timestamp.gz" | awk '{print $1}')

  #Compare.
  echo "Original size of $file: $original_size"
  echo "Compressed size of $file: $compressed_size"

done
